# Generated by Django 5.2.4 on 2025-07-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('done', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20),
        ),
    ]
